

fullMathExpression = multiplication, { additionOperator, multiplication } ;
multiplication = partMathExpression, { multiplicationOperator, partMathExpression } ;
partMathExpression = [ "-" ], ( number | variableName | functionCall | bracketedExpression ) ;
bracketedExpression = "(", fullMathExpression, ")"
